prepare:
  fetch:
    - "https://raw.githubusercontent.com/ProctorU/guides/master/style/ruby/.rubocop.yml"
    - "https://raw.githubusercontent.com/ProctorU/guides/master/style/scss/.scss-lint.yml"

plugins:
  fixme:
    enabled: true
  flog:
    enabled: true
  markdownlint:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
  scss-lint:
    enabled: true

exclude_patterns:
  - 'bin/'
  - 'test/'
  - 'assets/javascripts/hootstrap/modal.js' # 3rd party library
  - 'assets/javascripts/hootstrap/utils/dynamicListener.js' # 3rd party library
