title: Hootstrap
description: The CSS framework that powers ProctorU's front-end design.
url: https://proctoru.github.io/hootstrap

plugins:
  - jekyll-assets
  - hootstrap
  - jekyll-babel

assets:
  digest: false
